<a href="https://colab.research.google.com/github/vamshikrishna2001/LMMS_tryouts/blob/main/DecodingT5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install transformers datasets torch torchinfo

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 MB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 10.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.9/64.9 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 9.2 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (

In [2]:
import torch
from torch.utils.data import DataLoader
from transformers import AdamW , AutoModelForSeq2SeqLM , AutoTokenizer ,AutoModel
from datasets import load_dataset

In [3]:
dataset = load_dataset("knkarthick/dialogsum")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/12460 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/500 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1500 [00:00<?, ? examples/s]

In [4]:
model_name = 't5-small'
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

In [96]:
from transformers import T5Tokenizer, T5ForConditionalGeneration
tokenizer = T5Tokenizer.from_pretrained('t5-base')
modelSeq2Seq = T5ForConditionalGeneration.from_pretrained('t5-base')

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [97]:
modelSeq2Seq.lm_head

Linear(in_features=768, out_features=32128, bias=False)

In [98]:
prompt = "Capital of Brazil"

In [99]:
input_ids = tokenizer(prompt,return_tensors='pt').input_ids
tokenizer.convert_ids_to_tokens(list(input_ids.numpy()[0]))

['▁Capital', '▁of', '▁Brazil', '</s>']

In [18]:
input_ids

tensor([[5826,   13, 9278,    1]])

In [19]:
decoder_inputs = tokenizer('<pad>',add_special_tokens=False,return_tensors='pt').input_ids
decoder_inputs

tensor([[0]])

In [20]:
modelSeq2Seq.config.decoder_start_token_id

0

In [21]:
tokenizer.convert_ids_to_tokens([0])

['<pad>']

In [144]:
dash_line = ''.join('-' for i in range(100))
prompt = """
question: capital of India.
answer: capital of India is New Delhi

question: capital of Brazil.
answer: capital of Brazil is
"""

prompt = "tell me about brazil"

input_ids = tokenizer(prompt,return_tensors='pt').input_ids


print(dash_line)
print("prompt in tokens")
print(tokenizer.convert_ids_to_tokens(list(input_ids.numpy()[0])))
decoder_inputs = tokenizer('<pad>',add_special_tokens=False,return_tensors='pt').input_ids
print("decoder_inputs in tokens")
print(tokenizer.convert_ids_to_tokens(list(decoder_inputs.numpy()[0])))
print(dash_line)

with torch.no_grad():
  outputs = modelSeq2Seq(input_ids,decoder_input_ids = decoder_inputs, return_dict=True,output_hidden_states=True)
  next_decoder_input_ids = torch.argmax(outputs.logits,axis = -1)
  print("MODEL OUTPUT ")
  print(dash_line)
  print(tokenizer.convert_ids_to_tokens(next_decoder_input_ids.numpy()[0]))
  print(dash_line)
  decoder_input_ids = torch.cat([decoder_inputs, next_decoder_input_ids], axis=-1)
  print(decoder_input_ids)

  print(dash_line)
  print("encoder_hidden_states")
  # g = outputs.encoder_last_hidden_state
  g = outputs.encoder_hidden_states
  print(len(g))
  print(g[0].shape)

----------------------------------------------------------------------------------------------------
prompt in tokens
['▁tell', '▁me', '▁about', '▁bra', 'zi', 'l', '</s>']
decoder_inputs in tokens
['<pad>']
----------------------------------------------------------------------------------------------------
MODEL OUTPUT 
----------------------------------------------------------------------------------------------------
['<extra_id_0>']
----------------------------------------------------------------------------------------------------
tensor([[    0, 32099]])
----------------------------------------------------------------------------------------------------
encoder_hidden_states
13
torch.Size([1, 7, 768])


In [145]:
for i in range(100):
  with torch.no_grad():
    # outputs = modelSeq2Seq.forward(input_ids=None,encoder_outputs=(g,),decoder_input_ids=decoder_input_ids, return_dict=True,output_hidden_states=True)
    outputs = modelSeq2Seq.forward(input_ids=None,encoder_outputs=g,decoder_input_ids=decoder_input_ids, return_dict=True,output_hidden_states=True)
    next_decoder_input_ids = torch.argmax(outputs.logits,axis = -1)
    print("MODEL OUTPUT ")
    print(dash_line)
    print(tokenizer.convert_ids_to_tokens(next_decoder_input_ids.numpy()[0]))
    print(dash_line)
    decoder_input_ids = torch.cat([decoder_inputs, next_decoder_input_ids], axis=-1)
    predicted_tokens = tokenizer.convert_ids_to_tokens(decoder_input_ids.numpy()[0].tolist())
    print(tokenizer.convert_tokens_to_string(predicted_tokens)) # Pass the list of tokens here
    print(dash_line)
    print(outputs.encoder_last_hidden_state.shape)

MODEL OUTPUT 
----------------------------------------------------------------------------------------------------
['▁poveste', '▁Eck']
----------------------------------------------------------------------------------------------------
<pad>poveste Eck
----------------------------------------------------------------------------------------------------
torch.Size([1, 7, 768])
MODEL OUTPUT 
----------------------------------------------------------------------------------------------------
['▁poveste', '▁zi', 'zi']
----------------------------------------------------------------------------------------------------
<pad>poveste zizi
----------------------------------------------------------------------------------------------------
torch.Size([1, 7, 768])
MODEL OUTPUT 
----------------------------------------------------------------------------------------------------
['▁poveste', '▁zi', '▁cadouri', 'zi']
-----------------------------------------------------------------------------------

In [109]:
y = modelSeq2Seq.generate(input_ids = tokenizer(prompt,return_tensors='pt').input_ids)

/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1168: UserWarning: Using the model-agnostic default `max_length` (=20) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


In [138]:
prompt = "tell me about tje country Brazil ?"
inputs = tokenizer(prompt, return_tensors="pt")

In [139]:
with torch.no_grad():
    outputs = modelSeq2Seq.generate(inputs['input_ids'], max_length=50, num_beams=4, early_stopping=True)


In [140]:
answer = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(answer)

about tje country Brazil?
